import type { APIRoute } from 'astro'

export const prerender = true

export const GET: APIRoute = () => {
  const site = import.meta.env.SITE as string | undefined
  const siteUrl = site ? new URL(site) : undefined
  const sitemapEnabled = false
  const sitemapUrl =
    sitemapEnabled && siteUrl
      ? new URL('/sitemap-index.xml', siteUrl)
      : undefined

  const allowRobots = import.meta.env.VERCEL_ENV === 'production'

  return new Response(
    `# generated by Astro in src/pages/robots.txt.ts
User-agent: *
${allowRobots ? 'Allow' : 'Disallow'}: /
${siteUrl ? 'Host: ' + siteUrl.host : ''}
${sitemapUrl ? 'Sitemap: ' + sitemapUrl.href : ''}
`,
    {
      headers: {
        'content-type': 'text/plain'
      }
    }
  )
}
