export const keywords: string = [
  'HP tintas',
  'tóner HP',
  'impresoras HP',
  'suministros HP',
  'cartuchos de tinta HP',
  'tóner láser HP',
  'laptops HP',
  'computadoras HP',
  'accesorios HP',
  'repuestos HP',
  'impresoras multifuncionales HP',
  'scanners HP',
  'productos HP originales',
  'consumibles HP',
  'componentes de PC',
  'laptops para trabajo',
  'laptops para juegos',
  'componentes de computadora',
  'memorias RAM',
  'discos duros',
  'almacenamiento SSD',
  'teclados mecánicos',
  'monitores para oficina',
  'mouse ergonómico',
  'sillas para gaming',
  'fuentes de poder',
  'tarjetas gráficas',
  'torres de PC',
  'pantallas para computadoras',
  'periféricos de PC',
  'laptops portátiles',
  'suministros de oficina',
  'productos de tecnología',
  'accesorios de PC'
].join(', ')
